pcall(require, "luarocks.loader")
require("awful.autofocus")
require("init.async_errors_handler")
require("init.layouts")
require("init.mouse_workspace_controlls")
require("init.keyboard_workspace_controlls")
require("init.theme")
require("init.monitors_setup")
require("init.rules")
require("init.signals")